// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDDy-E4ZFrriCwiMEMzJ0q9A99wDG_pJA',
    appId: '1:459628958728:android:47be8cd005daf596e46dbd',
    messagingSenderId: '459628958728',
    projectId: 'interview-b2c73',
    authDomain: 'interview-b2c73.firebaseapp.com',
    storageBucket: 'interview-b2c73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDDy-E4ZFrriCwiMEMzJ0q9A99wDG_pJA',
    appId: '1:459628958728:android:47be8cd005daf596e46dbd',
    messagingSenderId: '459628958728',
    projectId: 'interview-b2c73',
    storageBucket: 'interview-b2c73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDDy-E4ZFrriCwiMEMzJ0q9A99wDG_pJA',
    appId: '1:459628958728:android:47be8cd005daf596e46dbd',
    messagingSenderId: '459628958728',
    projectId: 'interview-b2c73',
    storageBucket: 'interview-b2c73.firebasestorage.app',
    iosBundleId: 'app.exchange.ifortunex',
  );




}